services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    depends_on:
      - mssql
    ports:
     - "8000:8080"
    healthcheck:
      test: ["CMD-SHELL", "php -m | grep -q 'Core'"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongPass!123"
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPass!123"
    ports:
    - "1433:1433"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StrongPass!123' -C || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 40s